MODE 80
REM                   THIS DISK IS PUBLIC DOMAIN
REM                   --------------------------
REM
REM       MPW programmed by Fabio Pereira Rocha Mac (Brasil)
REM
REM
REM         It contains :    MPW 1.20 (English version)
REM                          MPW 1.20 DOC FILE (use MPW to read it)
REM
REM                   and... MPW 2.00 PREVIEW (256Kb is needed)
REM
REM
REM         Type :           MPW to execute MPW 1.20
REM                          MPW2 to start demo of MPW 2.00

